2025-08-21 09:33:46,302 - ERROR - Erro SQLAlchemy ao buscar Finalizações:
	Traceback (most recent call last):
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
	    self.dialect.do_execute(
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
	    cursor.execute(statement, parameters)
	psycopg2.errors.UndefinedTable: relation "finalizacao" does not exist
	LINE 2: FROM finalizacao ORDER BY finalizacao.finalizacao_id 
	             ^
	
	
	The above exception was the direct cause of the following exception:
	
	Traceback (most recent call last):
	  File "/home/davi/Downloads/keyControlApi/resources/FinalizarResource.py", line 21, in get
	    finalizacoes = db.session.execute(
	                   ^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 779, in execute
	    return self._proxied.execute(
	           ^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
	    return self._execute_internal(
	           ^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
	    result: Result[Any] = compile_state_cls.orm_execute_statement(
	                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
	    result = conn.execute(
	             ^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
	    return meth(
	           ^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
	    return connection._execute_clauseelement(
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
	    ret = self._execute_context(
	          ^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
	    return self._exec_single_context(
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
	    self._handle_dbapi_exception(
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
	    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
	    self.dialect.do_execute(
	  File "/home/davi/Downloads/keyControlApi/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
	    cursor.execute(statement, parameters)
	sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "finalizacao" does not exist
	LINE 2: FROM finalizacao ORDER BY finalizacao.finalizacao_id 
	             ^
	
	[SQL: SELECT finalizacao.finalizacao_id, finalizacao.reserva_id, finalizacao.data_hora_finalizacao 
	FROM finalizacao ORDER BY finalizacao.finalizacao_id 
	 LIMIT %(param_1)s OFFSET %(param_2)s]
	[parameters: {'param_1': 50, 'param_2': 0}]
	(Background on this error at: https://sqlalche.me/e/20/f405)
	
2025-08-21 09:35:41,594 - INFO - GET ALL - Listagem de Finalizações
2025-08-21 09:35:41,657 - INFO - Finalizações retornadas com sucesso
2025-08-21 09:35:48,425 - INFO - GET ALL - Listagem de Historicos
2025-08-21 09:35:48,428 - INFO - Historicos retornadas com sucesso
2025-08-21 09:35:51,294 - INFO - GET BY historico_id - historico 1
2025-08-21 09:35:57,627 - INFO - GET ALL - Listagem de Finalizações
2025-08-21 09:35:57,628 - INFO - Finalizações retornadas com sucesso
2025-08-21 09:36:03,662 - INFO - GET BY finalizacao_id - Finalização 1
